---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsbx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: adsbexchange
          image: mikenye/adsbexchange
          envFrom:
            - configMapRef:
                name: planespotting-config

          volumeMounts:
            - name: usb-adsb-receiver
              mountPath: $(USB_RECEIVER_PATH)
          securityContext:
            privileged: true
      volumes:
        - name: usb-adsb-receiver
          hostPath:
            path: $(USB_RECEIVER_PATH)
---
apiVersion: v1
kind: Service
metadata:
  name: adsbx
spec:
  ports:
    - port: 8080
      name: http
    - port: 30005
      name: beast
