---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tar1090
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: tar1090
          image: mikenye/tar1090
          envFrom:
            - configMapRef:
                name: planespotting-config
---
apiVersion: v1
kind: Service
metadata:
  name: tar1090
spec:
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tar1090
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - "$(TAR1090_HOST)"
      secretName: tar1090-tls
  rules:
    - host: "$(TAR1090_HOST)"
      http:
        paths:
          - backend:
              serviceName: tar1090
              servicePort: 80
            path: /
---
