apiVersion: v1
kind: Namespace
metadata:
  name: planespotting
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-readsb-from-tar1090
  namespace: planespotting
spec:
  podSelector:
    matchLabels:
      app: readsb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tar1090
      ports:
        - port: 30005
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-readsb-from-adsbx
  namespace: planespotting
spec:
  podSelector:
    matchLabels:
      app: readsb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: adsbx
      ports:
        - port: 30005
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-readsb-from-flightradar24
  namespace: planespotting
spec:
  podSelector:
    matchLabels:
      app: readsb
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: flightradar24
      ports:
        - port: 30005
          protocol: TCP
