---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piaware
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: piaware
          image: mikenye/piaware
          envFrom:
            - configMapRef:
                name: planespotting-config
---
apiVersion: v1
kind: Service
metadata:
  name: piaware
spec:
  ports:
    - port: 8754
      name: http
